Autogenerates files removed, update of some file due to some old one .m4 files
git-svn-id: svn://svn.gna.org/svn/freeciv-warclient/trunk@388 4efe6140-7f1d-0410-9bd2-be1ee28408da

diff --git a/warclient/configure b/warclient/configure
--- a/warclient/configure
+++ b/warclient/configure
@@ -673,6 +673,7 @@ AUTOCONF
 AUTOMAKE
 AUTOHEADER
 MAKEINFO
+AMTAR
 install_sh
 STRIP
 INSTALL_STRIP_PROGRAM
@@ -680,9 +681,6 @@ mkdir_p
 AWK
 SET_MAKE
 am__leading_dot
-AMTAR
-am__tar
-am__untar
 MAINTAINER_MODE_TRUE
 MAINTAINER_MODE_FALSE
 MAINT
@@ -705,7 +703,6 @@ am__fastdepCC_FALSE
 CPP
 GREP
 EGREP
-AUTH_CFLAGS
 AUTH_LIBS
 SERVER_TRUE
 SERVER_FALSE
@@ -1432,7 +1429,6 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-mysql-prefix=PFX   Prefix where MySQL is installed (optional)
   --with-readline         support fancy command line editing
   --with-xaw              use the Xaw widget set for the xaw client
   --with-xaw3d            use the Xaw3d widget set for the xaw client
@@ -2132,7 +2128,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-am__api_version="1.9"
+am__api_version="1.8"
 # Find a good install program.  We prefer a C program (faster),
 # so one script is as good as another.  But avoid the broken or
 # incompatible versions:
@@ -2285,21 +2281,13 @@ echo "$as_me: WARNING: \`missing' script is too old or missing" >&2;}
 fi
 
 if mkdir -p --version . >/dev/null 2>&1 && test ! -d ./--version; then
-  # We used to keeping the `.' as first argument, in order to
-  # allow $(mkdir_p) to be used without argument.  As in
+  # Keeping the `.' argument allows $(mkdir_p) to be used without
+  # argument.  Indeed, we sometimes output rules like
   #   $(mkdir_p) $(somedir)
-  # where $(somedir) is conditionally defined.  However this is wrong
-  # for two reasons:
-  #  1. if the package is installed by a user who cannot write `.'
-  #     make install will fail,
-  #  2. the above comment should most certainly read
-  #     $(mkdir_p) $(DESTDIR)$(somedir)
-  #     so it does not work when $(somedir) is undefined and
-  #     $(DESTDIR) is not.
-  #  To support the latter case, we have to write
-  #     test -z "$(somedir)" || $(mkdir_p) $(DESTDIR)$(somedir),
-  #  so the `.' trick is pointless.
-  mkdir_p='mkdir -p --'
+  # where $(somedir) is conditionally defined.
+  # (`test -n '$(somedir)' && $(mkdir_p) $(somedir)' is a more
+  # expensive solution, as it forces Make to start a sub-shell.)
+  mkdir_p='mkdir -p -- .'
 else
   # On NextStep and OpenStep, the `mkdir' command does not
   # recognize any option.  It will interpret all options as
@@ -2446,6 +2434,9 @@ AUTOHEADER=${AUTOHEADER-"${am_missing_run}autoheader"}
 
 MAKEINFO=${MAKEINFO-"${am_missing_run}makeinfo"}
 
+
+AMTAR=${AMTAR-"${am_missing_run}tar"}
+
 install_sh=${install_sh-"$am_aux_dir/install-sh"}
 
 # Installed binaries are usually stripped using `strip' when the user
@@ -2554,13 +2545,6 @@ INSTALL_STRIP_PROGRAM="\${SHELL} \$(install_sh) -c -s"
 
 # We need awk for the "check" target.  The system "awk" is bad on
 # some platforms.
-# Always define AMTAR for backward compatibility.
-
-AMTAR=${AMTAR-"${am_missing_run}tar"}
-
-am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
-
-
 
 
 
@@ -4335,18 +4319,8 @@ else
 fi
 
 
-
-# Check whether --with-mysql-prefix was given.
-if test "${with_mysql_prefix+set}" = set; then
-  withval=$with_mysql_prefix; mysql_prefix="$withval"
-else
-  mysql_prefix=""
-fi
-
-
   if test x$auth = xtrue; then
 
-    if test x$mysql_prefix = x; then
     if test "${ac_cv_header_mysql_mysql_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for mysql/mysql.h" >&5
 echo $ECHO_N "checking for mysql/mysql.h... $ECHO_C" >&6; }
@@ -4639,18 +4613,13 @@ fi
       else
         LDFLAGS=$fc_preauth_LDFLAGS
       fi
+
     done
-      AUTH_CFLAGS="$AUTH_CFLAGS"
-    else
-      AUTH_CFLAGS="-I$mysql_prefix/include $AUTH_CFLAGS"
-      AUTH_LIBS="-L$mysql_prefix/lib/mysql -lmysqlclient $AUTH_LIBS"
-    fi
 
     if test x$auth = xfalse; then
       { echo "$as_me:$LINENO: WARNING: can't find mysql -- disabling authentication" >&5
 echo "$as_me: WARNING: can't find mysql -- disabling authentication" >&2;}
     fi
-
 
 
 
@@ -9597,7 +9566,7 @@ cat >>confdefs.h <<\_ACEOF
 #define DEBUG 1
 _ACEOF
 
-  EXTRA_GCC_DEBUG_CFLAGS="$EXTRA_GCC_DEBUG_CFLAGS"
+  EXTRA_GCC_DEBUG_CFLAGS="$EXTRA_GCC_DEBUG_CFLAGS -Werror"
 else
   if test "x$enable_debug" = "xno"; then
 
@@ -9778,11 +9747,6 @@ _ACEOF
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_WINSOCK 1
-_ACEOF
-
-
-cat >>confdefs.h <<\_ACEOF
-#define NONBLOCKING_SOCKETS 1
 _ACEOF
 
   LIBS="$LIBS -lwsock32"
@@ -20759,13 +20723,9 @@ fi
 
 
 
-
-for ac_func in fcntl ioctl
-do
-as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
-{ echo "$as_me:$LINENO: checking for $ac_func" >&5
-echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6; }
-if { as_var=$as_ac_var; eval "test \"\${$as_var+set}\" = set"; }; then
+{ echo "$as_me:$LINENO: checking for fcntl" >&5
+echo $ECHO_N "checking for fcntl... $ECHO_C" >&6; }
+if test "${ac_cv_func_fcntl+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -20774,12 +20734,12 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+/* Define fcntl to an innocuous variant, in case <limits.h> declares fcntl.
    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
-#define $ac_func innocuous_$ac_func
+#define fcntl innocuous_fcntl
 
 /* System header to define __stub macros and hopefully few prototypes,
-    which can conflict with char $ac_func (); below.
+    which can conflict with char fcntl (); below.
     Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
     <limits.h> exists even on freestanding compilers.  */
 
@@ -20789,7 +20749,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 # include <assert.h>
 #endif
 
-#undef $ac_func
+#undef fcntl
 
 /* Override any GCC internal prototype to avoid an error.
    Use char because int might match the return type of a GCC
@@ -20797,18 +20757,18 @@ cat >>conftest.$ac_ext <<_ACEOF
 #ifdef __cplusplus
 extern "C"
 #endif
-char $ac_func ();
+char fcntl ();
 /* The GNU C library defines this for functions which it implements
     to always fail with ENOSYS.  Some functions are actually named
     something starting with __ and the normal name is an alias.  */
-#if defined __stub_$ac_func || defined __stub___$ac_func
+#if defined __stub_fcntl || defined __stub___fcntl
 choke me
 #endif
 
 int
 main ()
 {
-return $ac_func ();
+return fcntl ();
   ;
   return 0;
 }
@@ -20831,31 +20791,126 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  eval "$as_ac_var=yes"
+  ac_cv_func_fcntl=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	eval "$as_ac_var=no"
+	ac_cv_func_fcntl=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 fi
-ac_res=`eval echo '${'$as_ac_var'}'`
-	       { echo "$as_me:$LINENO: result: $ac_res" >&5
-echo "${ECHO_T}$ac_res" >&6; }
-if test `eval echo '${'$as_ac_var'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+{ echo "$as_me:$LINENO: result: $ac_cv_func_fcntl" >&5
+echo "${ECHO_T}$ac_cv_func_fcntl" >&6; }
+if test $ac_cv_func_fcntl = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FCNTL 1
 _ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define NONBLOCKING_SOCKETS 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: checking for ioctl" >&5
+echo $ECHO_N "checking for ioctl... $ECHO_C" >&6; }
+if test "${ac_cv_func_ioctl+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define ioctl to an innocuous variant, in case <limits.h> declares ioctl.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define ioctl innocuous_ioctl
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char ioctl (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef ioctl
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char ioctl ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_ioctl || defined __stub___ioctl
+choke me
+#endif
+
+int
+main ()
+{
+return ioctl ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_func_ioctl=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_func_ioctl=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_func_ioctl" >&5
+echo "${ECHO_T}$ac_cv_func_ioctl" >&6; }
+if test $ac_cv_func_ioctl = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IOCTL 1
+_ACEOF
+
 
 cat >>confdefs.h <<\_ACEOF
 #define NONBLOCKING_SOCKETS 1
 _ACEOF
 
 fi
-done
+
+fi
 
 
 { echo "$as_me:$LINENO: checking for SIGPIPE" >&5
@@ -21028,7 +21083,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-ac_config_files="$ac_config_files Makefile data/Makefile data/flags/Makefile data/misc/Makefile data/trident/Makefile data/isophex/Makefile data/isotrident/Makefile data/default/Makefile data/civ1/Makefile data/civ2/Makefile data/warruleset-1.2/Makefile data/warruleset-1.3/Makefile data/nowonder+1.2/Makefile data/tournament/Makefile data/duel/Makefile data/experimental/Makefile data/maps/Makefile data/scenario/Makefile data/nation/Makefile data/history/Makefile data/stdsounds/Makefile utility/Makefile utility/ftwl/Makefile common/Makefile common/aicore/Makefile ai/Makefile tests/Makefile win32/Makefile client/Makefile client/agents/Makefile client/include/Makefile client/gui-sdl/Makefile client/gui-gtk/Makefile client/gui-gtk-2.0/Makefile client/gui-xaw/Makefile client/gui-win32/Makefile client/gui-ftwl/Makefile client/gui-stub/Makefile server/Makefile server/generator/Makefile manual/Makefile intl/Makefile po/Makefile.in doc/Makefile doc/man/Makefile doc/de/Makefile doc/fr/Makefile doc/it/Makefile doc/ja/Makefile doc/nl/Makefile doc/sv/Makefile freeciv.spec:bootstrap/freeciv.spec.in bootstrap/undep.sh data/Freeciv client/freeciv.desktop:bootstrap/freeciv.desktop.in"
+ac_config_files="$ac_config_files Makefile data/Makefile data/flags/Makefile data/misc/Makefile data/trident/Makefile data/isophex/Makefile data/isotrident/Makefile data/default/Makefile data/civ1/Makefile data/civ2/Makefile data/warruleset-1.2/Makefile data/warruleset-1.3/Makefile data/nowonder+1.2/Makefile data/tournament/Makefile data/duel/Makefile data/experimental/Makefile data/maps/Makefile data/stdsounds/Makefile data/scenario/Makefile data/nation/Makefile data/history/Makefile utility/Makefile utility/ftwl/Makefile common/Makefile common/aicore/Makefile ai/Makefile tests/Makefile win32/Makefile client/Makefile client/agents/Makefile client/include/Makefile client/gui-sdl/Makefile client/gui-gtk/Makefile client/gui-gtk-2.0/Makefile client/gui-xaw/Makefile client/gui-win32/Makefile client/gui-ftwl/Makefile client/gui-stub/Makefile server/Makefile server/generator/Makefile manual/Makefile intl/Makefile po/Makefile.in doc/Makefile doc/man/Makefile doc/de/Makefile doc/fr/Makefile doc/it/Makefile doc/ja/Makefile doc/nl/Makefile doc/sv/Makefile freeciv.spec:bootstrap/freeciv.spec.in bootstrap/undep.sh data/Freeciv client/freeciv.desktop:bootstrap/freeciv.desktop.in"
 
 ac_config_files="$ac_config_files civ:bootstrap/civ.in"
 
@@ -21803,10 +21858,10 @@ do
     "data/duel/Makefile") CONFIG_FILES="$CONFIG_FILES data/duel/Makefile" ;;
     "data/experimental/Makefile") CONFIG_FILES="$CONFIG_FILES data/experimental/Makefile" ;;
     "data/maps/Makefile") CONFIG_FILES="$CONFIG_FILES data/maps/Makefile" ;;
+    "data/stdsounds/Makefile") CONFIG_FILES="$CONFIG_FILES data/stdsounds/Makefile" ;;
     "data/scenario/Makefile") CONFIG_FILES="$CONFIG_FILES data/scenario/Makefile" ;;
     "data/nation/Makefile") CONFIG_FILES="$CONFIG_FILES data/nation/Makefile" ;;
     "data/history/Makefile") CONFIG_FILES="$CONFIG_FILES data/history/Makefile" ;;
-    "data/stdsounds/Makefile") CONFIG_FILES="$CONFIG_FILES data/stdsounds/Makefile" ;;
     "utility/Makefile") CONFIG_FILES="$CONFIG_FILES utility/Makefile" ;;
     "utility/ftwl/Makefile") CONFIG_FILES="$CONFIG_FILES utility/ftwl/Makefile" ;;
     "common/Makefile") CONFIG_FILES="$CONFIG_FILES common/Makefile" ;;
@@ -21966,6 +22021,7 @@ AUTOCONF!$AUTOCONF$ac_delim
 AUTOMAKE!$AUTOMAKE$ac_delim
 AUTOHEADER!$AUTOHEADER$ac_delim
 MAKEINFO!$MAKEINFO$ac_delim
+AMTAR!$AMTAR$ac_delim
 install_sh!$install_sh$ac_delim
 STRIP!$STRIP$ac_delim
 INSTALL_STRIP_PROGRAM!$INSTALL_STRIP_PROGRAM$ac_delim
@@ -21973,9 +22029,6 @@ mkdir_p!$mkdir_p$ac_delim
 AWK!$AWK$ac_delim
 SET_MAKE!$SET_MAKE$ac_delim
 am__leading_dot!$am__leading_dot$ac_delim
-AMTAR!$AMTAR$ac_delim
-am__tar!$am__tar$ac_delim
-am__untar!$am__untar$ac_delim
 MAINTAINER_MODE_TRUE!$MAINTAINER_MODE_TRUE$ac_delim
 MAINTAINER_MODE_FALSE!$MAINTAINER_MODE_FALSE$ac_delim
 MAINT!$MAINT$ac_delim
@@ -21998,11 +22051,13 @@ am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
-AUTH_CFLAGS!$AUTH_CFLAGS$ac_delim
 AUTH_LIBS!$AUTH_LIBS$ac_delim
 SERVER_TRUE!$SERVER_TRUE$ac_delim
 SERVER_FALSE!$SERVER_FALSE$ac_delim
 CLIENT_TRUE!$CLIENT_TRUE$ac_delim
+CLIENT_FALSE!$CLIENT_FALSE$ac_delim
+FTWL_TRUE!$FTWL_TRUE$ac_delim
+FTWL_FALSE!$FTWL_FALSE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -22044,9 +22099,6 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-CLIENT_FALSE!$CLIENT_FALSE$ac_delim
-FTWL_TRUE!$FTWL_TRUE$ac_delim
-FTWL_FALSE!$FTWL_FALSE$ac_delim
 MAKE_DATA_TRUE!$MAKE_DATA_TRUE$ac_delim
 MAKE_DATA_FALSE!$MAKE_DATA_FALSE$ac_delim
 MAKE_CLIENT_INCLUDE_TRUE!$MAKE_CLIENT_INCLUDE_TRUE$ac_delim
@@ -22143,7 +22195,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 94; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -22162,7 +22214,7 @@ fi
 
 cat >>$CONFIG_STATUS <<_ACEOF
 cat >"\$tmp/subs-2.sed" <<\CEOF$ac_eof
-/@[a-zA-Z_][a-zA-Z_0-9]*@/!b
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
 _ACEOF
 sed '
 s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
@@ -22175,6 +22227,8 @@ N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
 ' >>$CONFIG_STATUS <conf$$subs.sed
 rm -f conf$$subs.sed
 cat >>$CONFIG_STATUS <<_ACEOF
+:end
+s/|#_!!_#|//g
 CEOF$ac_eof
 _ACEOF
 
@@ -22422,7 +22476,7 @@ s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed 's/|#_!!_#|//g' >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
@@ -22613,21 +22667,27 @@ echo X"$mf" |
   else
     continue
   fi
-  # Extract the definition of DEPDIR, am__include, and am__quote
-  # from the Makefile without running `make'.
+  grep '^DEP_FILES *= *[^ #]' < "$mf" > /dev/null || continue
+  # Extract the definition of DEP_FILES from the Makefile without
+  # running `make'.
   DEPDIR=`sed -n 's/^DEPDIR = //p' < "$mf"`
   test -z "$DEPDIR" && continue
-  am__include=`sed -n 's/^am__include = //p' < "$mf"`
-  test -z "am__include" && continue
-  am__quote=`sed -n 's/^am__quote = //p' < "$mf"`
   # When using ansi2knr, U may be empty or an underscore; expand it
   U=`sed -n 's/^U = //p' < "$mf"`
-  # Find all dependency output files, they are included files with
-  # $(DEPDIR) in their names.  We invoke sed twice because it is the
-  # simplest approach to changing $(DEPDIR) to its actual value in the
-  # expansion.
-  for file in `sed -n "
-    s/^$am__include $am__quote\(.*(DEPDIR).*\)$am__quote"'$/\1/p' <"$mf" | \
+  test -d "$dirpart/$DEPDIR" || mkdir "$dirpart/$DEPDIR"
+  # We invoke sed twice because it is the simplest approach to
+  # changing $(DEPDIR) to its actual value in the expansion.
+  for file in `sed -n '
+    /^DEP_FILES = .*\\\\$/ {
+      s/^DEP_FILES = //
+      :loop
+	s/\\\\$//
+	p
+	n
+	/\\\\$/ b loop
+      p
+    }
+    /^DEP_FILES = / s/^DEP_FILES = //p' < "$mf" | \
        sed -e 's/\$(DEPDIR)/'"$DEPDIR"'/g' -e 's/\$U/'"$U"'/g'`; do
     # Make sure the directory exists.
     test -f "$dirpart/$file" && continue
